import { ExpressionStrengthScorer } from "../scorers/ExpressionStrengthScorer";

const samples = [
  {
    text: "ok",
    features: {
      capsRatio: 0,
      exclamationCount: 0,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 0,
      messageCharLength: 2,
      hasText: true,
    },
  },
  {
    text: "OK!",
    features: {
      capsRatio: 0.5,
      exclamationCount: 1,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 0,
      messageCharLength: 3,
      hasText: true,
    },
  },
  {
    text: "OK!!!",
    features: {
      capsRatio: 0.5,
      exclamationCount: 3,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 0,
      messageCharLength: 5,
      hasText: true,
    },
  },
  {
    text: "no way",
    features: {
      capsRatio: 0,
      exclamationCount: 0,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 1,
      messageCharLength: 6,
      hasText: true,
    },
  },
  {
    text: "NO WAY!!!",
    features: {
      capsRatio: 0.8,
      exclamationCount: 3,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 1,
      messageCharLength: 9,
      hasText: true,
    },
  },
  {
    text: "I’m disappointed.",
    features: {
      capsRatio: 0,
      exclamationCount: 0,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 0,
      messageCharLength: 15,
      hasText: true,
    },
  },
  {
    text: "I am VERY disappointed!!!",
    features: {
      capsRatio: 0.2,
      exclamationCount: 3,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 1,
      interjectionCount: 0,
      messageCharLength: 24,
      hasText: true,
    },
  },
  {
    text: "what??",
    features: {
      capsRatio: 0,
      exclamationCount: 0,
      questionCount: 2,
      hasMixedPunctuation: false,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 1,
      messageCharLength: 6,
      hasText: true,
    },
  },
  {
    text: "WHAT?!?!",
    features: {
      capsRatio: 0.8,
      exclamationCount: 2,
      questionCount: 1,
      hasMixedPunctuation: true,
      emojiCount: 0,
      expressiveLengtheningCount: 0,
      intensifierCount: 0,
      interjectionCount: 1,
      messageCharLength: 7,
      hasText: true,
    },
  },
  {
    text: "noooo 😭😭",
    features: {
      capsRatio: 0,
      exclamationCount: 0,
      questionCount: 0,
      hasMixedPunctuation: false,
      emojiCount: 2,
      expressiveLengtheningCount: 1,
      intensifierCount: 0,
      interjectionCount: 1,
      messageCharLength: 8,
      hasText: true,
    },
  },
];

samples.forEach((sample) => {
  const result = ExpressionStrengthScorer.compute(sample.features);
  console.log(sample.text.padEnd(30), "→ ES:", result.es.toFixed(3));
});