export const featureFlags = Object.freeze({
  appraisalBridgeEnabled: process.env.LORA_APPRAISAL_BRIDGE === '1',
  appraisalBridgeModeEnabled: process.env.LORA_APPRAISAL_BRIDGE_MODE === '1',
  appraisalPacingHintEnabled: process.env.LORA_APPRAISAL_PACING_HINT === '1',
  strictGuidanceModeEnabled: process.env.LORA_STRICT_GUIDANCE_MODE === '1',
  driftMonitorEnabled: process.env.LORA_DRIFT_MONITOR === '1',
  validationIntensityEnabled: process.env.LORA_VALIDATION_INTENSITY === '1',
  adaptiveOverrideCooldownEnabled: process.env.LORA_ADAPTIVE_OVERRIDE_COOLDOWN === '1',
  appraisalToneHintEnabled: process.env.LORA_APPRAISAL_TONE_HINT === '1',
  interventionValidationHintEnabled: process.env.LORA_INTERVENTION_VALIDATION_HINT === '1',
  interventionPacingHintEnabled: process.env.LORA_INTERVENTION_PACING_HINT === '1',
  interventionToneHintEnabled: process.env.LORA_INTERVENTION_TONE_HINT === '1',
  interventionActionHintEnabled: process.env.LORA_INTERVENTION_ACTION_HINT === '1',
  interventionInterruptHintEnabled: process.env.LORA_INTERVENTION_INTERRUPT_HINT === '1',
  interventionStepHintEnabled: process.env.LORA_INTERVENTION_STEP_HINT === '1',
  interventionQuestionBudgetEnabled: process.env.LORA_INTERVENTION_QUESTION_BUDGET === '1',
  hintResolverEnabled: process.env.LORA_HINT_RESOLVER === '1',
  hintStickinessEnabled: process.env.LORA_HINT_STICKINESS === '1',
  guidanceDwellLockEnabled: process.env.LORA_GUIDANCE_DWELL_LOCK === '1',
  hintSemanticGuardEnabled: process.env.LORA_HINT_SEMANTIC_GUARD === '1',
  etvV1Enabled: process.env.LORA_ETV_V1 === '1',
  etvPolicyPromptEnabled: process.env.LORA_ETV_POLICY_PROMPT === '1',
  etvPolicyPromptShadowEnabled: process.env.LORA_ETV_POLICY_PROMPT_SHADOW === '1',
  memoryV1Enabled: process.env.LORA_MEMORY_V1 === '1',
  memoryV1ShadowEnabled: process.env.LORA_MEMORY_V1_SHADOW === '1',
  memoryV1DebugEnabled: process.env.LORA_MEMORY_V1_DEBUG === '1',
});
